### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/core#2] opened 2015-09-15 22:15 UTC
Replicate BS3 Alert Component

**Comment by Foxandxss** [comment] 2015-09-15 22:16
No.

**Comment by BobbieBarker** [comment] 2015-09-15 23:14
I'll take a stab at this one.

**Comment by Foxandxss** [comment] 2015-09-15 23:14
No, this one is on hold for the time being.

**Comment by BobbieBarker** [comment] 2015-09-15 23:15
oh?

**Comment by pkozlowski-opensource** [comment] 2015-10-29 15:06
WIP here: https://github.com/pkozlowski-opensource/ng2-bs/blob/master/src/alert/alert.ts
Will be opening a PR shortly

**Comment by Foxandxss** [comment] 2015-10-29 15:09
On phone atm, so I can't check the implementation. I don't like the uibs
one, so I want to do something different in here.

**Comment by Foxandxss** [comment] 2015-10-29 16:21
Ok, I can explain myself correctly now.

@pkozlowski-opensource Problem I See with your uibs alert is that the user needs to create all the infrastructure on their HTML and handle the closing of the alerts. I would like to avoid at least the last part in here. Perhaps it needs to be all or nothing.

I imagined this like a mini toastr, where you dynamically put alerts on screen and then they go away. Not sure how feasible is that as today.

**Comment by pkozlowski-opensource** [comment] 2015-10-29 17:06
> Problem I See with our uibs alert is that the user needs to create all the infrastructure on their HTML 

Could you elaborate?

> and handle the closing of the alerts. 

Yes, indeed, this is an issue. But I'm not sure how we could make it better with the current ng2. The whole philosophy of it is that you know "statically" the structure of HTML. So we can't just "disappear" 

We could wrap the whole alert in a div or even hide a host element, yeh. Do you have any proposal here?

**Comment by Foxandxss** [comment] 2015-10-29 17:14
So our uibs alert is like:

```html
<uib-alert ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)">{{alert.msg}}</uib-alert>
```

The problem is that you need to go to a template and add it by hand. Then the alerts are on a list that you need to populate to show them. For closing them, you need a function in your controller to delete items of the list.

It is not that user friendly imho.

On the other hand in my [angular-toastr](https://github.com/Foxandxss/angular-toastr) I have a dynamic container (that could that html I pasted) that is generated and inserted into the body (or any other element) automatically when a toastr is shown. Then they get closed by timeout.

So instead of having a list hanging somewhere that will populate a list of alerts, you have a service where you do `toastr.success('foo');`.

Toasts comes to screen, they generate DOM, they disappear, they clean all their stuff.

I thought about a mini toastr for alerts, so you don't really need to have a place to put the DOM container, the list of alerts, being able to clean them in the userland...

**Comment by pkozlowski-opensource** [comment] 2015-10-29 17:18
@Foxandxss what you are describing here is a different use-case IMO - I'm not saying we shouldn't support it but I see the value of simple alert thingy which I can stick where I want in a markup.

What you are describing is like a service (similar to modals in a way) which definitively has value but IMO should be here in _addition_ to a simple component. The problem to be solve here would be: how do we anchor those alerts? How do you express where those should show up on a screen?

**Comment by Foxandxss** [comment] 2015-10-29 17:20
I can see what you say. Our bigger issue was that to implement the dismiss on timeout, you need the user to actually dismiss the alerts.

About your question. I don't follow what you mean.

**Comment by pkozlowski-opensource** [comment] 2016-05-12 18:51
OK, so after chatting with different people in the Angular team, here is my proposal:
* let's keep the current alert component as is - it will serve as a "static" component that people can use in various situations
* let's add another directive that could be used like so:

```html
<template ngbAlert>
   Alert's content
</template>
```

By putting alert on a template element we make it clear that it can be dismissed / destroyed it in the way that doesn't leave any traces in the final DOM. Adding support for dismissing on timeout would be trivial as well.

Implementation should be super-simple, here is a sketch of it (it still needs wiring-up inputs / outputs):

```javascript
import {Directive, TemplateRef, ViewContainerRef, ComponentFactory, ComponentResolver, Injector} from '@angular/core';
import {NgbAlert} from './alert';

@Directive({
  selector: 'template[ngb-alert]'
})
export class NgbAlertDismissible {
  constructor(private _vcRef: ViewContainerRef, private _tplRef: TemplateRef<any>, private _cr: ComponentResolver, private _injector: Injector) {
  }

  ngOnInit() {
    this._cr.resolveComponent(NgbAlert).then((cf: ComponentFactory<NgbAlert>) => {
      var rootNodes = this._tplRef.createEmbeddedView({}).rootNodes;
      this._vcRef.createComponent(cf, 0, this._injector, [rootNodes]);
    });
  }
}
```

**Comment by Foxandxss** [comment] 2016-05-12 18:55
Sounds good but I admit I am a bit behind on all of this <template> and advanced stuff. But sounds interesting.

**Comment by icfantv** [comment] 2016-05-12 22:25
Don't forget `implements OnInit`.

**Comment by pkozlowski-opensource** [comment] 2016-06-13 09:52
Closing this in favor of more focused #206 and #207

**Closed by pkozlowski-opensource** 2016-06-13 09:52 UTC
Labels: component: alert, needs: work
